LICENSE

Show example

---

.github/workflows/lint-action.yml

Add lint workflow

---

package-lock.json
package.json

issue nr#7 -Add css framework -irinamihai150
I have installed react bootstrap
Fixes #1

issue nr#7 -Add css framework -irinamihai150

---

db/migrations/20230212203435_firstTable.js
db/migrations/20230212212502_add_class_Number_to_Users.js
db/seeds/01_region.js
db/seeds/02_users.js
knexfile.js
package-lock.json
package.json

#6 - Setup Database Migration - Hayat

---

client/src/index.js

I missed a line in installing react bootstrap
Fixes #1
#7

 # 7 add css line in index

---

db/migrations/20230213124754_skillsTable.js
db/seeds/03_skills.js

#6-Database Migrations-Vanipriya

---

client/src/learning_objectives.json

Add fake learning objectives

---

client/src/App.js
client/src/pages/Home.css
client/src/pages/Home.js
client/src/pages/Mentor.js
package-lock.json
package.json
server/api.js

list of students and scores, api endpointfakedata
Fixes 
#3

  ISSUENUMBER #3 -irinamihai

---

.vscode/settings.json
client/src/pages/Home.js
client/src/pages/Login.js
package-lock.json
package.json
server/api.js

Loging form (componenet ) with haspassword created and endpoint for for checking password created but haven't checked with the database yet.
Fixes #16

Login flow 

---

db/migrations/20230215133221_new_users.js
package-lock.json
package.json

Added a new migration

---

db/seeds/02_users.js
db/seeds/04_new_users.js

Some data has been added to new user table

---

db/migrations/20230215205134_uSer_learning_Obj.js
db/seeds/05_learning_objectives.js
db/seeds/06_user_learning_objectives.js
package-lock.json
package.json
select app.json client db Dockerfile knexfile.js LICENSE manifest.yml node_modules nodemon.json package.json package-lock.json README.md render.yaml server from user_learning_obj

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME#
#6 irinamihai
Fixes #1
#6

Data migrate

---

client/src/pages/Footer.js
client/src/pages/Home.css
client/src/pages/Home.js

Adding footer component   #23 irinamihai
Fixes #1
#23

Adding a footer component

---

client/src/App.js
client/src/learning_objectives.json
client/src/pages/Header.css
client/src/pages/Home.css
client/src/pages/Mentor.js
client/src/pages/SignupForm.js
db/migrations/20230215133221_new_users.js
db/seeds/02_users.js
db/seeds/04_new_users.js
db/seeds/05-02_learning_objectives.js
server/api.js

#6-Add new seeds in learning objectives

---

client/src/pages/Home.css
client/src/pages/Skills.js

Fix skillJS classname

---

client/src/pages/Mentor.js
server/api.js

#3 Mentor summary irinamihai
added another column to table and, correcting an error
Fixes #1
#3

#3 Mentor Summary irinamihai

---

client/src/App.js
client/src/pages/Home.css
client/src/pages/Home.js
client/src/pages/Login.js
server/api.js

Fixed routings

---

client/src/pages/Home.css
client/src/pages/Student.js
db/seeds/05_03_learning_objectives.js

#6-Add new learning objectives to database-Vanipriya

---

package-lock.json
package.json
server/api.js
server/app.js

Add cookie session

---

client/src/App.js
client/src/pages/Student.js
server/api.js

#37-Add flow to save scores for a user-Vanipriya

---

db/migrations/20230221145723_add_timestamp_to_user_learning_obj.js

#6-add migration for timestamp column to user learning obj-Vanipriya

---

db/migrations/20230221190148_user_total_score_table.js

Add student total score table

---

client/src/pages/Student.js
client/src/pages/TableOfScores.js
client/src/pages/UserScores.js
server/api.js

#37-add a button to display user recent scores-Vanipriya

---

client/src/pages/Footer.js
client/src/pages/SignupForm.js
server/api.js

Kawa signupform

---

client/src/pages/Home.css
client/src/pages/Login.js
package-lock.json
package.json
server/api.js

Front end of Forget Password+ new css file for login+signup+forgetpassword forms

---

client/src/pages/ForgetPassword.js
client/src/pages/UserProfile.js
client/src/pages/loginSignUp.css

Newfiles forget password

---

client/src/App.js
client/src/pages/Header.js
server/api.js

End point for use profile added again

---

client/src/App.js
client/src/pages/Profile.js
client/src/pages/Skills.js
client/src/pages/Student.js
client/src/pages/TableOfScores.js
client/src/pages/UsersProfile.css

add css framework for profile page

---

client/src/pages/Profile.js

change image link

---

client/src/pages/Footer.css
client/src/pages/Footer.js
client/src/pages/Header.js
client/src/pages/Home.css
client/src/pages/Login.js
client/src/pages/SignupForm.js
client/src/pages/loginSignUp.css
package-lock.json
package.json
server/api.js

Signup modifed+ some more work on forget password

---

client/src/pages/AddNewObjective.js
client/src/pages/Home.css
client/src/pages/LearningObjective.js
client/src/pages/Mentor.css
client/src/pages/Mentor.js
client/src/pages/ObjectiveRow.js
server/api.js

#34 create learning page irinamihai
mentor is able to view add and delete learning objectives
Fixes #1
#34

Learningobj2

---

client/src/App.js
client/src/pages/Student.js
client/src/pages/TableOfScores.js
client/src/pages/UserScores.js
server/api.js

get session user id in backend

---

client/src/pages/Chart.js
client/src/pages/Profile.js
package-lock.json
package.json
server/api.js

add student progress chart for each skills in user profile 
Fixes #64

#64-add progress chart for student-Vanipriya

---

db/migrations/20230226184306_add_resources_table.js
db/seeds/07_resources.js

I have created a migration for resources table and seed some data. Each skill has at least one resource. I decided not to include the learning objectives in the new table, because if we want a resource for every learning objective, we will be talking of more than 100 resources for complete representation.
Fixes #71

#71-Added resource - Hayat

---

client/src/pages/Chart.js
client/src/pages/Profile.js
client/src/pages/TableOfAllScores.js

I added the scores per skills  table for user in user profile section
Fixes #64

#64-add the scores per skills table for user-Vanipriya

---

client/src/App.js
client/src/pages/Footer.css
client/src/pages/Home.js
client/src/pages/HomePage.css
client/src/pages/HomePage.js
client/src/pages/Login.js

add home page and responsive login page

---

client/src/pages/HomePage.js
client/src/pages/Profile.js
client/src/pages/TableOfAllScores.js

fix image name

---

client/src/App.css
client/src/App.js
client/src/pages/Chart.js
client/src/pages/ClassCodeDropdown.js
client/src/pages/Footer.css
client/src/pages/Footer.js
client/src/pages/HomePage.css
client/src/pages/Login.js
client/src/pages/Mentor.css
client/src/pages/Mentor.js
client/src/pages/Profile.js
client/src/pages/RegionDropdown.js
client/src/pages/TableOfAllScores.js
client/src/pages/login.css

Footer positioning fixed+ more page for dark mode

---

client/src/App.js
client/src/pages/AddNewObjective.js
client/src/pages/LandingPageMentor.js
client/src/pages/LearningObj.css
client/src/pages/LearningObjective.js
client/src/pages/Login.js
client/src/pages/Mentor.js
client/src/pages/ObjectiveRow.js

#67 landing page irinamihai
i have added a mentor landing page and corrected some css so all page can be consistent
Fixes #1
#67 
#67

Mentorlandingpage

---

client/src/App.js
client/src/pages/AllResources.js
client/src/pages/Chart.js
client/src/pages/LandingPage.js
client/src/pages/MoreResources.js
client/src/pages/Skill.json
server/api.js

I added the cards for each skill, when they click the cards it gives the link for more resources, this link leads to the more resources page
Fixes #67

#67-add more resources for each skills in landing page-Vanipriya

---

client/src/pages/AllResources.css
client/src/pages/AllResources.js
client/src/pages/Chart.css
client/src/pages/Chart.js

add css framework to skill-banners

---

client/src/pages/AddNewObjective.js
client/src/pages/LearningObjective.js
client/src/pages/Mentor.css
client/src/pages/Mentor.js
client/src/pages/ObjectiveRow.js
server/api.js

#93 prevent edit learning irinamihai
i completed prevent learning objectives
Fixes #1
#93

Preventediting

---

client/src/App.js
client/src/pages/AllResources.js
client/src/pages/Assessment.js
client/src/pages/Skill.json
server/api.js

add assessment in landing page-Vanipriya

---

client/src/pages/AddNewObjective.js
client/src/pages/LearningObjective.js
client/src/pages/Mentor.js
client/src/pages/ObjectiveRow.js

add sort and fix css

---

client/src/pages/LandingPage.js
client/src/pages/Profile.js
client/src/pages/Resources.js
server/api.js

Add final score on profile page

---

client/src/pages/Chart.js
client/src/pages/LandingPage.js
client/src/pages/Profile.js
client/src/pages/Resources.js
package-lock.json
package.json
server/api.js

I modified the api endpoint for final-scores, user profile,resource
Fixes #1

fix api endpoint-finalscore-Vanipriya

---

client/src/pages/Login.js
client/src/pages/Resources.js
client/src/pages/SignupForm.js

Add reading time & enforce case insensitive username

---

client/src/pages/AllResources.js

change-skill-banner-display

---

client/src/pages/AddNewObjective.js
client/src/pages/LearningObjective.js
client/src/pages/Mentor.js
client/src/pages/ObjectiveRow.js
server/api.js

Fixingerror

---

client/src/App.js
client/src/pages/AddNewObjective.js
client/src/pages/Assessment.js
client/src/pages/LearningObjective.js
client/src/pages/Mentor.js
client/src/pages/MoreResources.js
client/src/pages/ObjectiveRow.js
client/src/pages/Profile.js
client/src/pages/Skills.js
client/src/pages/Student.js

Conflict Resolved mainly wity Mentor+LO pages+finilzied darkmode
Fixes #1

Conflict+finlizing+darkmode

---

client/src/pages/AddNewObjective.js
client/src/pages/LearningObjective.js
client/src/pages/ObjectiveRow.js

Update LO without Refresh
Drop down list of skill improved
icon deleted and update changed to be more consist
Fixes #1

Update LO without Refresh

---

client/src/pages/AddNewObjective.js
client/src/pages/LearningObj.css
client/src/pages/LearningObjective.js
client/src/pages/Mentor.css
client/src/pages/Mentor.js
client/src/pages/ObjectiveRow.js
client/webpack/dev.config.js
server/api.js

#120 irinamihai
update objective no longer needs refresh to be updated, 
I fixed the updated objective that needed a refresh to be updated. also, change CSS to be consistent with the same pages.
Fixes #1
#120

fixing updatebug plus change css

---

client/src/pages/AllResources.js
client/src/pages/LandingPage.js
client/src/pages/LandingPageMentor.js
client/src/pages/Profile.js
client/src/pages/Student.js
client/src/pages/TableOfAllScores.js
client/src/pages/TableOfScores.js
client/src/pages/UserScores.js
server/api.js

add css-framework in all student page

---

client/src/pages/LearningObjective.js

#99  add css to learning objective irinamihai
i have change the page because the skills were repeating many times so mi made them just one time..
Fixes #1
#99

Refactorlearning obj

---

client/src/pages/Footer.js
db/migrations/20230307185403_collectEmail.js
db/seeds/09_subscription.js
server/api.js

Finalise Subscription

---

client/src/pages/ClassCodeDropdown.js
client/src/pages/LearningObjective.js

Kawa polishing fixing bugs1

---

client/src/pages/Mentor.css
client/src/pages/Mentor.js
client/src/pages/UserScores.js

fix the studentList table columns

---

client/src/pages/About.js
client/src/pages/AddNewObjective.js
client/src/pages/LandingPageMentor.js
client/src/pages/LearningObjective.js

Improve texts on mentor & about pages

---

client/src/pages/Chart.js
client/src/pages/Mentor.js
client/src/pages/Profile.js
client/src/pages/TableOfAllScores.js
server/api.js

I modified the api for getting students score list for each skills, and added another api for showing student progress chart and scores table for the menters
Fixes #1

Modify api student list score
